// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module "vue" {
  export interface GlobalComponents {
    ABreadcrumbItem: typeof import("ant-design-vue/es")["BreadcrumbItem"]
    AFormItem: typeof import("ant-design-vue/es")["FormItem"]
    ATextarea: typeof import("ant-design-vue/es")["Textarea"]
    Breadcrumb: typeof import("./src/components/breadcrumb.vue")["default"]
    Navigate: typeof import("./src/components/navigate.vue")["default"]
    UploadImg: typeof import("./src/components/tools/UploadImg.vue")["default"]
  }
}

export { }
