// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    ACol: typeof import('ant-design-vue/es')['Col']
    AComment: typeof import('ant-design-vue/es')['Comment']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    AList: typeof import('ant-design-vue/es')['List']
    AListItem: typeof import('ant-design-vue/es')['ListItem']
    AListItemMeta: typeof import('ant-design-vue/es')['ListItemMeta']
    ARow: typeof import('ant-design-vue/es')['Row']
    AsyncButton: typeof import('D:/ropo/mvp/Daosheng/src/components/ui/asyncButton.vue')['default']
    ChinaEmotion: typeof import('D:/ropo/mvp/Daosheng/src/components/home/weibo/chinaEmotion.vue')['default']
    Comment: typeof import('D:/ropo/mvp/Daosheng/src/components/home/weiboComment/comment.vue')['default']
    CommentList: typeof import('D:/ropo/mvp/Daosheng/src/components/home/weiboComment/commentList.vue')['default']
    Emotion: typeof import('D:/ropo/mvp/Daosheng/src/components/home/weibo/emotion.vue')['default']
    Header: typeof import('D:/ropo/mvp/Daosheng/src/components/home/header.vue')['default']
    UploadImg: typeof import('D:/ropo/mvp/Daosheng/src/components/tools/UploadImg.vue')['default']
  }
}

export { }
