/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/wb/wordcloud/{id}": {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** 成功 */
        200: {
          content: {
            "application/json": {
              code: string;
              msg: string;
              success: boolean;
              data: components["schemas"]["%E8%AF%8D%E4%BA%91"];
            };
          };
        };
      };
    };
  };
  "/api/softConfig/get": {
    get: {
      parameters: {};
      responses: {
        /** 成功 */
        200: {
          content: {
            "application/json": components["schemas"]["%E8%BD%AF%E4%BB%B6%E4%BF%A1%E6%81%AF"];
          };
        };
      };
    };
  };
  "/api/wb/top/most/list": {
    post: {
      parameters: {};
      responses: {
        /** 成功 */
        200: {
          content: {
            "application/json": {
              msg: string;
              code: number;
              data: components["schemas"]["%E7%83%AD%E5%BA%A6%E6%8E%92%E5%90%8D"];
              /** 是否成功 */
              success: boolean;
            };
          };
        };
      };
      requestBody: {
        content: {
          "application/json": {
            date: string;
          };
        };
      };
    };
  };
  "/api/user/login": {
    post: {
      parameters: {};
      responses: {
        /** 成功 */
        200: {
          content: {
            "application/json": components["schemas"]["%E7%99%BB%E5%BD%95%E8%BF%94%E5%9B%9E%E5%80%BC"];
          };
        };
      };
      requestBody: {
        content: {
          "application/json": {
            code: string;
            password: string;
          };
        };
      };
    };
  };
  "/api/wb/top/most/trend/chart": {
    post: {
      parameters: {};
      responses: {
        /** 成功 */
        200: {
          content: {
            "application/json": {
              msg: string;
              code: number;
              data: components["schemas"]["%E8%BF%9130%E5%A4%A9%E7%83%AD%E5%BA%A6%E8%B5%B0%E5%8A%BF"];
              /** 是否成功 */
              success: boolean;
            };
          };
        };
      };
      requestBody: {
        content: {
          "application/json": {
            date: string;
          };
        };
      };
    };
  };
}

export interface components {
  schemas: {
    登录返回值: {
      success: boolean;
      message?: string;
      data?: {
        code: string;
        name: string;
        role: string;
        token: string;
      };
    };
    热度排名: {
      /** 事件名称 */
      keyword: string;
      /**
       * 热度
       * @description long类型数值
       */
      heat: number;
      /**
       * 事件Id
       * @description 功能主键
       * @default 1
       */
      id: string;
    }[];
    "全局响应结果-热度排名(试用)": {
      msg: string;
      code: number;
      data: {
        keyword: string;
        heat: number;
        id: string;
      }[];
    };
    近30天热度走势: {
      date: string[];
      list: {
        /** @description 热搜名字 */
        name: string;
        /** @description 热搜近30天数据（按照时间排序） */
        data: number[];
        id: string;
      }[];
    };
    词云: {
      value: number;
      name: string;
    }[];
    软件信息: {
      copyRightValue: string;
      softName: string;
      success: boolean;
      useCas: string;
      message: string | null;
    };
    login: {
      code: string;
      password: string;
    };
  };
}

export interface operations {}

export interface external {}
