/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/softConfig/get": {
    get: {
      parameters: {};
      responses: {
        /** 成功 */
        200: {
          content: {
            "application/json": components["schemas"]["%E8%BD%AF%E4%BB%B6%E4%BF%A1%E6%81%AF"];
          };
        };
      };
    };
  };
}

export interface components {
  schemas: {
    热度排名: {
      /** 事件名称 */
      keyword: string;
      /**
       * 热度
       * @description long类型数值
       */
      heat: number;
    }[];
    软件信息: {
      copyRightValue: string;
      softName: string;
      success: boolean;
      useCas: string;
      message: string | null;
    };
  };
}

export interface operations {}

export interface external {}
